// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './EditPatentCell'
import type { EditPatentById, EditPatentByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditPatentCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof EditPatentById | 'updating'
> & EditPatentByIdVariables

export default function (props: CellInputs): ReturnType<SuccessType>
