// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './SavedDrugCell'
import type { FindSavedDrugQuery, FindSavedDrugQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './SavedDrugCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindSavedDrugQuery | 'updating'
> & FindSavedDrugQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
