// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './ExpiringSoonCell'
import type { FindExpiringSoonQuery, FindExpiringSoonQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './ExpiringSoonCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindExpiringSoonQuery | 'updating'
> & FindExpiringSoonQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
