// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './PostsCell'
import type { POSTS, POSTSVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './PostsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof POSTS | 'updating'
> & POSTSVariables

export default function (props: CellInputs): ReturnType<SuccessType>
