// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './EditDrugCell'
import type { EditDrugById, EditDrugByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditDrugCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof EditDrugById | 'updating'
> & EditDrugByIdVariables

export default function (props: CellInputs): ReturnType<SuccessType>
