// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './DrugPatentsCell'
import type { DrugPatentsQuery, DrugPatentsQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './DrugPatentsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof DrugPatentsQuery | 'updating'
> & DrugPatentsQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
