// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './EditSavedDrugCell'
import type { EditSavedDrugById, EditSavedDrugByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditSavedDrugCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof EditSavedDrugById | 'updating'
> & EditSavedDrugByIdVariables

export default function (props: CellInputs): ReturnType<SuccessType>
