// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './ActivePatentsPerCompanyCell'
import type { FindActivePatentsPerCompanyQuery, FindActivePatentsPerCompanyQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './ActivePatentsPerCompanyCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindActivePatentsPerCompanyQuery | 'updating'
> & FindActivePatentsPerCompanyQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
