// This file was generated by RedwoodJS
import FatalErrorPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/HomePage/HomePage'
import NotFoundPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/NotFoundPage/NotFoundPage'
import DrugDrugPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Drug/DrugPage/DrugPage'
import DrugDrugsPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Drug/DrugsPage/DrugsPage'
import DrugEditDrugPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Drug/EditDrugPage/EditDrugPage'
import DrugNewDrugPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Drug/NewDrugPage/NewDrugPage'
import PatentEditPatentPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Patent/EditPatentPage/EditPatentPage'
import PatentNewPatentPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Patent/NewPatentPage/NewPatentPage'
import PatentPatentPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Patent/PatentPage/PatentPage'
import PatentPatentsPageType from 'C:/Users/tyler/Desktop/redwood-tutorial/web/src/pages/Patent/PatentsPage/PatentsPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const DrugDrugPage: typeof DrugDrugPageType
  const DrugDrugsPage: typeof DrugDrugsPageType
  const DrugEditDrugPage: typeof DrugEditDrugPageType
  const DrugNewDrugPage: typeof DrugNewDrugPageType
  const PatentEditPatentPage: typeof PatentEditPatentPageType
  const PatentNewPatentPage: typeof PatentNewPatentPageType
  const PatentPatentPage: typeof PatentPatentPageType
  const PatentPatentsPage: typeof PatentPatentsPageType
}
