// This file was generated by RedwoodJS
import DrugPatentsPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/DrugPatentsPage/DrugPatentsPage'
import FatalErrorPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/FatalErrorPage/FatalErrorPage'
import HomePageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/HomePage/HomePage'
import NotFoundPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/NotFoundPage/NotFoundPage'
import SavedPatentsPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/SavedPatentsPage/SavedPatentsPage'
import DrugDrugPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Drug/DrugPage/DrugPage'
import DrugDrugsPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Drug/DrugsPage/DrugsPage'
import DrugEditDrugPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Drug/EditDrugPage/EditDrugPage'
import DrugNewDrugPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Drug/NewDrugPage/NewDrugPage'
import PatentEditPatentPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Patent/EditPatentPage/EditPatentPage'
import PatentNewPatentPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Patent/NewPatentPage/NewPatentPage'
import PatentPatentPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Patent/PatentPage/PatentPage'
import PatentPatentsPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/Patent/PatentsPage/PatentsPage'
import SavedDrugEditSavedDrugPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/SavedDrug/EditSavedDrugPage/EditSavedDrugPage'
import SavedDrugNewSavedDrugPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/SavedDrug/NewSavedDrugPage/NewSavedDrugPage'
import SavedDrugSavedDrugPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/SavedDrug/SavedDrugPage/SavedDrugPage'
import SavedDrugSavedDrugsPageType from 'C:/Users/surface/Desktop/drugpatents-redwood/web/src/pages/SavedDrug/SavedDrugsPage/SavedDrugsPage'

declare global {
  const DrugPatentsPage: typeof DrugPatentsPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const HomePage: typeof HomePageType
  const NotFoundPage: typeof NotFoundPageType
  const SavedPatentsPage: typeof SavedPatentsPageType
  const DrugDrugPage: typeof DrugDrugPageType
  const DrugDrugsPage: typeof DrugDrugsPageType
  const DrugEditDrugPage: typeof DrugEditDrugPageType
  const DrugNewDrugPage: typeof DrugNewDrugPageType
  const PatentEditPatentPage: typeof PatentEditPatentPageType
  const PatentNewPatentPage: typeof PatentNewPatentPageType
  const PatentPatentPage: typeof PatentPatentPageType
  const PatentPatentsPage: typeof PatentPatentsPageType
  const SavedDrugEditSavedDrugPage: typeof SavedDrugEditSavedDrugPageType
  const SavedDrugNewSavedDrugPage: typeof SavedDrugNewSavedDrugPageType
  const SavedDrugSavedDrugPage: typeof SavedDrugSavedDrugPageType
  const SavedDrugSavedDrugsPage: typeof SavedDrugSavedDrugsPageType
}
