// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './PatentsCell'
import type { FindPatents, FindPatentsVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './PatentsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindPatents | 'updating'
> & FindPatentsVariables

export default function (props: CellInputs): ReturnType<SuccessType>
