// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './SavedDrugsCell'
import type { SavedDrugsQuery, SavedDrugsQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './SavedDrugsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof SavedDrugsQuery | 'updating'
> & SavedDrugsQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
