// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './BlogPostsCell'
import type { BlogPostsQuery, BlogPostsQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './BlogPostsCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof BlogPostsQuery | 'updating'
> & BlogPostsQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
