// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './DrugPatentCell'
import type { FindDrugPatentQuery, FindDrugPatentQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './DrugPatentCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindDrugPatentQuery | 'updating'
> & FindDrugPatentQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
