// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './TotalPatentsPerCompanyCell'
import type { FindTotalPatentsPerCompanyQuery, FindTotalPatentsPerCompanyQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './TotalPatentsPerCompanyCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindTotalPatentsPerCompanyQuery | 'updating'
> & FindTotalPatentsPerCompanyQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
