// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './RecentlyExpiredCell'
import type { FindRecentlyExpiredQuery, FindRecentlyExpiredQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './RecentlyExpiredCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindRecentlyExpiredQuery | 'updating'
> & FindRecentlyExpiredQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
