// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './EditPostCell'
import type { FindPostById, FindPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditPostCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindPostById | 'updating'
> & FindPostByIdVariables

export default function (props: CellInputs): ReturnType<SuccessType>
