// This file was generated by RedwoodJS
import type { ComponentProps } from 'react'

import { Success } from './PatentAggregateCell'
import type { FindPatentAggregateQuery, FindPatentAggregateQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './PatentAggregateCell'

type CellInputs = Omit<
  ComponentProps<SuccessType>,
  keyof QueryOperationResult | keyof FindPatentAggregateQuery | 'updating'
> & FindPatentAggregateQueryVariables

export default function (props: CellInputs): ReturnType<SuccessType>
